
name: 'eth'
version: '1.0.0'

profile: 'eth'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  eth:
    +materialized: table
    marts:
        +tags:
          - powerbi
          - reports  
        +schema: marts

        analytics:
         stablecoin_activity_per_day:
           +post-hook:
             - grant select on table DBT.DBT_NITESH_MARTS.stablecoin_activity_per_day to role ba
             - grant usage on database dbt to role ba
             - grant usage on schema DBT.DBT_NITESH_MARTS to role ba
             - grant usage on warehouse compute_wh to role ba
           +grants:
             select: ['ba']   
