version: 2

models:
    - name: stg_transactions
      description: "{{ doc('transactions') }}"
      columns:
        - name: hash
          description: this is a hash desc
          data tests:
          - unique
          - not null
    
    - name: stablecoin_activity_per_day
      config:
        contract:
         enforced: true 
      columns:
      - name: date
        data_type: date

      - name: token_address
        data_type: varchar

      - name: total_usd_value
        data_type: float

    - name: transactions_enriched
      columns:
        - name: value
          tests:
          - generic_test_value_is_positive

    - name: stablecoin_activity_per_day_v1
      columns:
        - name: type
          data_type: varchar
          data_tests:
            - accepted_values:
                values: ['Hybrid','Fiat-backed','Crypto-backed']

    - name: stg_token_transfers
      columns:
        - name: transaction_hash
          data_tests:
            - relationships:
                to: ref('stg_transactions')
                field: hash

exposures:

  - name: stablecoin_activity_per_day_v1
    type: dashboard

    depends_on:
      - ref('stg_token_transfers')
      - ref('stablecoins')
    owner:
      name: nit
      email: nit@email.com                