version: 2

models:
    - name: stg_transactions
      columns:
        - name: hash
          description: this is a hash desc
          data tests:
          - unique
          - not null
    
    - name: stablecoin_activity_per_day
      config:
        contract:
         enforced: true 
      columns:
      - name: date
        data_type: date

      - name: token_address
        data_type: varchar

      - name: total_usd_value
        data_type: float
